#!/bin/sh

if [ -z "$AUTOSTART_LOADED" ]; then
  . $HOME/.config/autostart/init
else
  . $HOME/.config/autostart/reload
fi

bspc monitor -d I/TERM II/WEB III/DOC IV/EDIT V/FILE VI/MAIL VII/CHAT VIII/MEDIA IX/VM X/MUSIC
#bspc monitor -d {I,II,III,IV,V,VI,VII,VIII,IX,X}

bspc config border_width         1
bspc config normal_border_color  "$XRES_BACKGROUND"
bspc config active_border_color  "$XRES_FOREGROUND"
bspc config focused_border_color "$XRES_NORMAL_BLUE"

bspc config window_gap     30
bspc config top_padding    38
bspc config bottom_padding 47

bspc config split_ratio           0.50
bspc config borderless_monocle    false
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config history_aware_focus   true

# Rules
bspc rule -r "*"

# II : Browser workspace
bspc rule -a Firefox desktop=^2

# III: Reading workspace
bspc rule -a Zathura state=tiled center=on

# IV : Editing workspace
bspc rule -a Gimp desktop=^4 center=on

# VII: Chat wordspace
bspc rule -a TelegramDesktop desktop=^7 center=on
bspc rule -a discord         desktop=^7 center=on
bspc rule -a Skype           desktop=^7 center=on

# Multimedia rules
bspc rule -a Feh  state=floating center=on
bspc rule -a Sxiv state=floating center=on
bspc rule -a mpv  state=floating center=on

# Make dragon follow users's workspace focus
bspc rule -a Dragon state=floating center=on sticky=on

