; mkconfig default build template.
; Change these variables accordingly.

[modules]
; dirs storing modules, separated by a colon
path = setup/modules
; files to ignore inside path (globbing is allowed)
ignore_files =
; whether hidden files should be ignored (1) or not (0)
ignore_hidden = 1

[build]
; file to build
path = zathurarc

[substitute]
; whether xrdb colors will be substituted (1) or not (0)
xrdb-colors = 1
; The sequence to parse and substitute
; Here $s is considered the string to substitute from the
; variables below.
sub-sequence = %$s
;
hello = world
