;: Icons :;
[icons]
app-term    = 
app-browser = 
app-mail    = 
app-files   = 
app-music   = ﭵ
app-edit    = 
app-chat    = 
app-launch  = 
app-calen   = 
app-clock   = 

mp-prev   = <
mp-next   = >
mp-play   = @
mp-stop   = ©
mp-pause  = #
;mp-random = 
mp-cursor = 
mp-fill   = 
mp-empty  = 籠

