### Zsh Environment ###

export PAGER="less"
export EDITOR="nvim"

export VIMINIT="source $HOME/.config/vim/vimrc"

export LF_ICONS='\
	tw=:st=:ow=:dt=:di=:\
	fi=:ln=:or=:ex=:\
	*.desktop=:*.o=:*.torrent=:\
	*.c=ﭰ:*.cc=ﭱ:*.h=ﭰ:\
	*.hh=ﭱ:*.hpp=ﭱ:*.cpp=ﭱ:\
	*.clj=:*.coffee=:*.css=:\
	*.d=:*.dart=:*.erl=:\
	*.exs=:*.fs=:*.go=:\
	*.hs=:*.html=:*.java=:\
	*.jl=:*.js=:*.json=:\
	*.lua=:*.md=:*.php=:\
	*.pl=:*.pro=:*.py=:\
	*.cr=:*.rb=:*.rs=:\
	*.xml=:*.exe=:*.psd=:\
	*.scala=:*.ts=:*.vim=:\
	*.vdi=:*.vdk=:\
	*.vbox=:*.vbox-prev=:\
	*.cfg=:*.conf=:*.ini=:\
	*.cmd=:*.ps1=:*.sh=:\
	*.bash=:*.zsh=:*.fish=:\
	*.tar=:*.tgz=:*.arc=:\
	*.arj=:*.taz=:*.lha=:\
	*.lz4=:*.lzh=:*.lzma=:\
	*.tlz=:*.txz=:*.tzo=:\
	*.t7z=:*.zip=:*.z=:\
	*.dz=:*.gz=:*.lrz=:\
	*.lz=:*.lzo=:*.xz=:\
	*.zst=:*.tzst=:*.bz2=:\
	*.bz=:*.tbz=:*.tbz2=:\
	*.tz=:*.deb=:*.rpm=:\
	*.jar=:*.war=:*.ear=:\
	*.sar=:*.rar=:*.alz=:\
	*.ace=:*.zoo=:*.cpio=:\
	*.7z=:*.rz=:*.cab=:\
	*.wim=:*.swm=:*.dwm=:\
	*.esd=:\
	*.jpg=:*.jpeg=:*.mjpg=:\
	*.mjpeg=:*.gif=:*.bmp=:\
	*.pbm=:*.pgm=:*.ppm=:\
	*.tga=:*.xbm=:*.xpm=:\
	*.tif=:*.tiff=:*.png=:\
	*.svg=:*.svgz=:*.mng=:\
	*.pcx=:\
	*.mov=:*.mpg=:*.mpeg=:\
	*.m2v=:*.mkv=:*.webm=:\
	*.ogm=:*.mp4=:*.m4v=:\
	*.mp4v=:*.vob=:*.qt=:\
	*.nuv=:*.wmv=:*.asf=:\
	*.rm=:*.rmvb=:*.flc=:\
	*.avi=:*.fli=:*.flv=:\
	*.gl=:*.dl=:*.xcf=:\
	*.xwd=:*.yuv=:*.cgm=:\
	*.emf=:*.ogv=:*.ogx=:\
	*.aac=ﭵ:*.au=ﭵ:*.flac=ﭵ:\
	*.m4a=ﭵ:*.mid=ﭵ:*.midi=ﭵ:\
	*.mka=ﭵ:*.mp3=ﭵ:*.mpc=ﭵ:\
	*.ogg=ﭵ:*.ra=ﭵ:*.wav=ﭵ:\
	*.oga=ﭵ:*.opus=ﭵ:\
	*.spx=:*.xspf=:\
	*.key=:*.keys=:\
	*.theme=:\
	*.pdf=:\
	*.nix=:\
	*.sav=:*.dsv=:\
	*.nds=:*.3ds=\'

export PATH="$PATH:\
	/usr/local/bin:\
	/usr/local/sbin:\
	/usr/local/games:\
	/usr/lib/jvm/java-8-oracle/bin:\
	/usr/lib/jvm/java-8-oracle/db/bin:\
	/usr/lib/jvm/java-8-oracle/jre/bin:\
	/usr/bin:\
	/usr/sbin:\
	/usr/games:\
	/bin:\
	/sbin:\
	/snap/bin:\
	/home/nin93/bin:\
	/usr/local/go/bin:\
	/home/nin93/go/bin"
