### Zsh Configuration File ###

### Workflow ###
setopt auto_cd

# Use Vi keys
bindkey -v
# Navigate through selection menu
#bindkey -M menuselect 'h' vi-backward-char
#bindkey -M menuselect 'j' vi-down-line-or-history
#bindkey -M menuselect 'k' vi-up-line-or-history
#bindkey -M menuselect 'l' vi-forward-char

# Enable Ctrl+s Ctrl+q
setopt noflowcontrol

stty start undef
stty stop undef


### Prompt ###
setopt prompt_subst

RPROMPT=''
PROMPTPWD="%B%(!.%F{magenta}.%F{cyan})%31<…<%1~%f %(?.%#.%F{red}%#%f)%b "
PROMPT=$'${PROMPTPWD}'


### Plugins / Extensions ###
source $ZDOTDIR/.zalias

#source $ZDOTDIR/plugins/login.plugin.zsh
source $ZDOTDIR/plugins/crystal.zsh
source $ZDOTDIR/plugins/git-status.zsh
# https://github.com/zsh-users/zsh-syntax-highlighting
source $ZDOTDIR/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh


### History ###
setopt histignorealldups sharehistory

HISTSIZE=1000
SAVEHIST=1000
HISTFILE=$ZDOTDIR/.zhistory


### Completions ###
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
#zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select
#zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

#PATH='/usr/local/sbin:\
#	/usr/local/bin:\
#	/usr/sbin:\
#	/usr/bin:\
#	/sbin:\
#	/bin:\
#	/usr/games:\
#	/usr/local/games:\
#	/snap/bin:\
#	/usr/lib/jvm/java-8-oracle/bin:\
#	/usr/lib/jvm/java-8-oracle/db/bin:\
#	/usr/lib/jvm/java-8-oracle/jre/bin:\
#	/home/nin93/bin:\
#	/usr/local/go/bin:\
#	/home/nin93/go/bin'
