;: System :;
[module/updates]
inherit = module/generic
type    = custom/script

exec = eix --installed --upgrade --only-names | wc -l
interval = 60.0

format-prefix = %{T2}ﮮ%{T-}

format = <label>
label = %output%


[module/cpu]
inherit = module/generic
type    = internal/cpu

label = %percentage%%

format-prefix = "%{T2}%{T-}"


[module/memory]
inherit = module/generic
type    = internal/memory

label = %percentage_used%%

format-prefix = "%{T2}%{T-}"


[module/eth]
inherit = module/generic
type    = internal/network

interface = enp1s0

interval = 5.0

format-connected-prefix = "%{T2}直%{T-}"
label-connected = %local_ip%

format-disconnected-prefix = "%{T2}睊%{T-}"
label-disconnected = no network

label-connected-padding = ${self.label-padding}
label-disconnected-padding = ${self.label-padding}


[module/powermenu]
type = custom/menu

expand-right = false

format-spacing = 0

label-open = ⏼
label-open-foreground = ${colors.secondary}

label-close = " ⏼"
label-close-foreground = ${colors.secondary}

label-separator = " |"
label-separator-foreground = ${colors.foreground}

menu-0-0 = " reboot"
menu-0-0-exec = sudo reboot
menu-0-1 = " power off"
menu-0-1-exec = sudo poweroff
