;: Time :;
[module/clock]
inherit = module/generic
type    = internal/date

format-prefix = %{T2}%{T-}

label = %time%

time = %H:%M


[module/date]
inherit = module/generic
type    = internal/date

format-prefix = %{T2}%{T-}

label = %date%

date = %a %d %b %Y
date-alt = %d-%m-%Y
