;: MPD :;
[module/mpd-controller]
inherit = module/generic
type    = internal/mpd

;icon-prev  = <
;icon-stop  = ©
;icon-play  = @
;icon-pause = #
;icon-next  = >

icon-prev  = %{T2}寧%{T-}
icon-stop  = ${icons.mp-stop}
icon-play  = %{T2}%{T-}
icon-pause = %{T2}懶%{T-}
icon-next  = %{T2}嶺%{T-}

format-offline =
format-online  = <icon-prev> <toggle> <icon-next>


[module/mpd-progress]
inherit = module/generic
type    = internal/mpd

format-offline =
format-online  = <label-time>

label-time = [%elapsed% ~ %total%]

bar-progress-width     = 13
bar-progress-indicator = ${icons.mp-cursor}
bar-progress-fill      = ${icons.mp-fill}
bar-progress-empty     = ${icons.mp-empty}


[module/mpd-song]
inherit = module/generic
type    = internal/mpd

format-offline = offline

format-online         = <label-song>
format-online-prefix  = %{T2}%{T-}

label-song         = %artist% ~ %album% * %title%
label-song-padding = ${self.label-padding}

label-song-maxlen   = 80
label-song-ellipsis = true


;: Audio :;
[module/pulseaudio]
type = internal/pulseaudio

format-volume = <label-volume> <ramp-volume>

label-volume = VOL %percentage%%
label-volume-foreground = ${colors.foreground}

label-muted = 🔇
label-muted-foreground = ${colors.foreground}


[module/alsa]
inherit = module/generic
type = internal/alsa

format-volume = <label-volume>
format-volume-prefix = "%{T2}奔%{T-}"

label-volume = %percentage%%
label-volume-padding = ${self.label-padding}

format-muted-prefix = "%{T2}ﱝ%{T-}"
label-muted-padding = ${self.label-padding}
